## import modules

In [267]:
import math
import torch
import torch.nn as nn
import numpy as np

## Initialize Linear Layer 

In [268]:
# we assume a 256-dimensional input and a 4-dimensional output for this 1-layer neural network
# hence, we initialize a 256x4 dimensional matrix filled with random values
weights = torch.randn(256, 4) / math.sqrt(256)
# we then ensure that the parameters of this neural network ar trainable, that is,
#the numbers in the 256x4 matrix can be tuned with the help of backpropagation of gradients
weights.requires_grad_()
# finally we also add the bias weights for the 4-dimensional output, and make these trainable too
bias = torch.zeros(4, requires_grad=True)
x = torch.randn(256)
alinear0 = torch.matmul(x, weights) + bias
print(alinear0)

alinear1 = nn.Linear(256, 4)

with torch.no_grad():
    alinear1.weight.copy_(weights.T)
    alinear1.bias.copy_(bias.T)

print(alinear0)
print(alinear1(x))

tensor([-0.1346, -0.0673, -1.4666,  0.1236], grad_fn=<AddBackward0>)
tensor([-0.1346, -0.0673, -1.4666,  0.1236], grad_fn=<AddBackward0>)
tensor([-0.1346, -0.0673, -1.4666,  0.1236], grad_fn=<AddBackward0>)


## Initialize with PCA

In [269]:

num_features = 20
num_components = 9
num_patterns = 300

x = torch.randn((num_patterns, num_features))
x_new = ((x - torch.min(x)) / (torch.max(x) - torch.min(x)))  # interval 0 to 1
U, S, V = torch.pca_lowrank(x_new, q=num_components, center=True, niter=30)
weights = V[:, :num_components] 
#print(V.size())

weights.requires_grad_()
bias = torch.randn(num_components, requires_grad=True)

alinear1 = torch.matmul(x_new, weights ) + bias
scaled = 2*(((alinear1 - torch.min(alinear1)) / (torch.max(alinear1) - torch.min(alinear1))) - 0.5)  #  interval -1 to 1

#print(scales)
print(scaled.size())

torch.Size([20, 9])
torch.Size([300, 9])
