## import modules

In [115]:
import torch
import numpy as np

In [116]:
arr0 = torch.tensor([[3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
print(arr0)
print(arr0.shape)

tensor([[3., 4., 5.],
        [6., 7., 8.]])
torch.Size([2, 3])


In [117]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
t_array1 = torch.from_numpy(arr1)
print(t_array1)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [118]:
torch.manual_seed(0)
arr3 = torch.rand((2,3))
print(arr3)
print(arr3.shape)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341]])
torch.Size([2, 3])


In [119]:
print(arr0 + arr3)

tensor([[3.4963, 4.7682, 5.0885],
        [6.1320, 7.3074, 8.6341]])


In [120]:
print(arr0 * arr3)

tensor([[1.4888, 3.0729, 0.4424],
        [0.7922, 2.1520, 5.0726]])


In [121]:
print(arr0.T.matmul(arr3))
print(arr3.T.matmul(arr0).T)

tensor([[2.2810, 4.1492, 4.0699],
        [2.9092, 5.2248, 4.7925],
        [3.5375, 6.3005, 5.5150]])
tensor([[2.2810, 4.1492, 4.0699],
        [2.9092, 5.2248, 4.7925],
        [3.5375, 6.3005, 5.5150]])


In [122]:
bias = torch.tensor([30.0, 40.0, 50.0])
print(arr0 + bias)

tensor([[33., 44., 55.],
        [36., 47., 58.]])
